### ISSUE TITLE
New Practice: Readme contains necessary content

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#396]
## New Practice Proposal

Create a practice to check if the README file contains necessary headlines.

*Proposal:*
Readme contains... 
- exactly one `<h1>` or `#` headline
- `<h2>` or `##` headline for "Getting Started"
- `<h3>` or `###` headline for "Prerequisites"
- `<h3>` or `###` headline for "Installing" or "Installation"
- `<h2>` or `##` headline for "Contributing" or "Contribution"
- `<h2>` or `##` headline for "License"

Any other proposals are welcomed!

*Notes:*
- There already exists a practice `ReadmeIsPresentPractice.ts`.
- The new practice depends on `ReadmeIsPresentPractice.ts`.

**Comment by iamRishabh07** [comment]
Hi, @prokopsimek I would like to work on this issue.

**Comment by prokopsimek** [comment]
@iamRishabh07 Sure! Go for it! 🎉

**Comment by king-11** [comment]
@prokopsimek the issue has been stale for a while now . @iamRishabh07 if you aren't working on it can i start working?

**Comment by adelkahomolova** [comment]
Since @iamRishabh07 has an open pull request in our repository for quite a long time, I think you can take this one @king-11 :)

**Comment by king-11** [comment]
@adelkahomolova need a bit of help... 
```typescript
const files = await ctx.fileInspector.scanFor(regexReadme, '/', { shallow: true });
const rootFiles = await ctx.root.fileInspector.scanFor(regexReadme, '/', { shallow: true });
```

here an array of files is returned so should I check for the content specified in the issue to be in at least one of the files or something else ?

**Comment by adelkahomolova** [comment]
Hi, @king-11 , you should use the same approach as the [JsGitignoreCorrectlySetPractice](https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts#L35). So use the 
```js
const rootFiles = await ctx.root.fileInspector.readFile(pathToReadme, '/', { shallow: true });
```
Also, don't forget to add `dependsOn` in the decorator. This practice depends on ReadmeIsPresent
Same as [JsGitignoreCorrectlySetPractice](https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts#L15) depends on [GitignoreIsPresentPractice](https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/LanguageIndependent/GitignoreIsPresentPractice.ts)
It should look like 
```js
dependsOn: { practicing: ['LanguageIndependent.ReadmeIsPresent'] },
```
By adding this you can be sure the Readme file exists, so you can directly use `.readFile()` method instead of `.scanFor()` it first.

Did I answer your questions? :)

**Comment by king-11** [comment]
@adelkahomolova I guess the arguments for readFile are a bit different :no_mouth: and basically the issue I am having is that readme can be name as : 
- README.md
- readme.md
- Readme.md
so how shall I deal with this because in [GitignoreIsPresentPractice](https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/LanguageIndependent/GitignoreIsPresentPractice.ts) we are using regex search but here a single file is needed

**Comment by adelkahomolova** [comment]
You can use [lowerCase method](https://lodash.com/docs/4.17.15#lowerCase) from lodash, so it will unify the string and all the three variants will be the same. After that, you can work with that as you want. Did I answer your question? @king-11 :)

**Comment by adelkahomolova** [comment]
Sorry, I see the problem now 🙈 . But I don't think the method is case-sensitive. Have you tried it? @king-11

**Comment by king-11** [comment]
Moved through a lot of functions and at the end it's using ```fs.readFile()``` which doesn't seem to be case-insensitive as per the documentation, case-sensitivity for node seems to depend on the system we are using as per this [Link](https://nodejs.org/en/docs/guides/working-with-different-filesystems/#unicode-form-preservation)

**Comment by king-11** [comment]
![Screenshot_20201022_173748](https://user-images.githubusercontent.com/52061363/96869622-59889680-148d-11eb-8527-c77b29192e52.png)

@adelkahomolova I wrote this but it doesn't seem to be working so I guess will have to use scanFor but in that shall I select the first file that is returned in the array for checking if correctly set or not?

**Comment by king-11** [comment]
I was thinking something like this to get file contents
```typescript
const regexReadme = new RegExp('readme', 'i');

    const files = await ctx.fileInspector.scanFor(regexReadme, '/', { shallow: true });
    const rootFiles = await ctx.root.fileInspector.scanFor(regexReadme, '/', { shallow: true });

    let content: string;
    if (files.length !== 0) {
      const fileName = files[0].name;
      content = await ctx.fileInspector.readFile(fileName);
    } else {
      const fileName = rootFiles[0].name;
      content = await ctx.root.fileInspector.readFile(fileName);
    }
```

**Comment by adelkahomolova** [comment]
Ok, use the `scanFor()`. Thank you, that you've tried it ❤️ , you were right. :) 
It seems fine to me. :)  @king-11
