### ISSUE TITLE
Log CLI runs to file to be able collect logs from users

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#76]
_As a user who figured out an error in DX Scanner, I would like to have a log file where I can copy&paste the log result to a new issue on Github in DX Scanner repository._

**Definition of done:**
- all runs of DX Scanner are logged to a file in the root (or /tmp) folder
- the log contains all errors, debugs and basic project configuration
- the log has hidden secrets

Read [our Contribution guide](https://github.com/DXHeroes/dx-scanner/blob/master/CONTRIBUTING.md).

**Comment by vypxl** [comment]
I would like to work on this. Could someone explain to me what 'hidden secrets' is about?

**Comment by vypxl** [comment]
Also, if all debugs are enabled, a scan of this repo results in a 24 megabyte logfile, is that the goal?

**Comment by vypxl** [comment]
Another question: Should other commands such as init and practices also be logged?

**Comment by adelkahomolova** [comment]
Hi, @vypxl , thank you for your interest in contributing to our repository!
To your questions:
1) Hidden secrets mean, that if you paste for example your access token to the GitHub (which is needed by dx-scanner if you scan the private repository), this secret should not be shown in the log file, so if user has some error and want to send to someone he won't send it with his secrets.
2) All the information that is logged in `debug` mode should be collected in file.

Did I answer your questions? :)

**Comment by vypxl** [comment]
Yes, thanks. I assume my third question is answered with a yes?

**Comment by adelkahomolova** [comment]
It should be logged, if it's logged in `debug` mode @vypxl :)

**Comment by vypxl** [comment]
Ok, [This](https://pastebin.com/kxP4U4sv) is what I got so far, when scanning this repo with my `-l` flag: `dx-scanner -l run`.
Is this everything that is needed?

I also have one problem: Any Ideas on how to close the logfile to flush? When registering a `beforeExit` handler, the logfile is missing some content, if the process gets terminated by `process.exit(code)`. And because flushing the file is asynchronous, I cannot do that in an `exit` handler.
I figured that I could somehow replace the existing calls to `process.exit`, with something else, such as setting `process.exitCode` and then letting the process exit normally. Any hints on this?

**Comment by prokopsimek** [comment]
@vypxl Hi, may you show us your code, please? I haven't found a linked PR to this issue.

I guess there exists any command for loggers to flush all remaining context before exit but I am not sure how you implemented this functionality.

Thanks 👍
